version: "3.7"
services:

  jupyter:
    build:
      context: ./
      target: dev
    env_file:
      - .env
    volumes:
      - ./:/project:delegated
    ports:
      - "8888:8888"
    command: jupyter lab --allow-root

