version: "3.7"
services:

  web:
    build:
      context: ./
      target: dev
    env_file:
      - .env
      - .env-local
    volumes:
      - ./:/project:delegated
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000
