[tool.ruff]
select = [
  "F", # pyflakes
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "I", # isort
  "N", # pep8-naming
  "UP", # pyupgrade
  "ANN", # flake8-annotations
  "S", # flake8-bandit
  "A", # flake8-builtins
  "COM", # flake8-commas
  "C4", # flake8-comprehensions
  "DTZ", # flake8-datetimez
  "INP", # flake8-no-pep420
  "PIE", # flake8-pie
  "T20", # flake8-print
  "RET", # flake8-return
  "SIM", # flake8-simplify
  "ARG", # flake8-unused-arguments
  "PTH", # flake8-use-pathlib
  "RUF100", # yesqa
]

ignore = [
  "ANN101", # missing-type-self
  "E501", # line-too-long
  "INP001", # implicit package - grafana folder
]
